"""init schema

Revision ID: c718542c1dca
Revises: 
Create Date: 2026-08-27 20:53:03.130893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c718542c1dca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potreros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('capacity_estimate', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('drone_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('potrero_id', sa.Integer(), nullable=False),
    sa.Column('drone_identifier', sa.String(length=60), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('en_progreso','completada','fallida')", name='ck_drone_missions_status'),
    sa.ForeignKeyConstraint(['potrero_id'], ['potreros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drone_missions_potrero_id'), 'drone_missions', ['potrero_id'], unique=False)
    op.create_table('livestock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_code', sa.String(length=40), nullable=False),
    sa.Column('alias', sa.String(length=80), nullable=True),
    sa.Column('species', sa.String(length=40), nullable=False),
    sa.Column('breed', sa.String(length=80), nullable=True),
    sa.Column('potrero_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('activo','vendido','fallecido','perdido')", name='ck_livestock_status'),
    sa.ForeignKeyConstraint(['potrero_id'], ['potreros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_code')
    )
    op.create_index(op.f('ix_livestock_potrero_id'), 'livestock', ['potrero_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('imagen','video')", name='ck_media_type'),
    sa.ForeignKeyConstraint(['mission_id'], ['drone_missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_mission_id'), 'media', ['mission_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('livestock_id', sa.Integer(), nullable=True),
    sa.Column('potrero_id', sa.Integer(), nullable=False),
    sa.Column('bbox_x', sa.Numeric(), nullable=False),
    sa.Column('bbox_y', sa.Numeric(), nullable=False),
    sa.Column('bbox_width', sa.Numeric(), nullable=False),
    sa.Column('bbox_height', sa.Numeric(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('behavior', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("behavior IN ('pastoreo','descanso','anomalo','desconocido')", name='ck_detections_behavior'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_detections_confidence'),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['potrero_id'], ['potreros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_detected_at'), 'detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_detections_livestock_id'), 'detections', ['livestock_id'], unique=False)
    op.create_index(op.f('ix_detections_media_id'), 'detections', ['media_id'], unique=False)
    op.create_index(op.f('ix_detections_potrero_id'), 'detections', ['potrero_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('livestock_id', sa.Integer(), nullable=True),
    sa.Column('potrero_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('baja','media','alta','critica')", name='ck_alerts_priority'),
    sa.CheckConstraint("status IN ('activa','en_revision','resuelta','descartada')", name='ck_alerts_status'),
    sa.CheckConstraint("type IN ('comportamiento_anomalo','animal_faltante','animal_desconocido','salud','sistema')", name='ck_alerts_type'),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ),
    sa.ForeignKeyConstraint(['potrero_id'], ['potreros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_potrero_id'), 'alerts', ['potrero_id'], unique=False)
    op.create_index(op.f('ix_alerts_priority'), 'alerts', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_priority'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_potrero_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_detections_potrero_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_media_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_livestock_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detected_at'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_media_mission_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_livestock_potrero_id'), table_name='livestock')
    op.drop_table('livestock')
    op.drop_index(op.f('ix_drone_missions_potrero_id'), table_name='drone_missions')
    op.drop_table('drone_missions')
    op.drop_table('potreros')
    # ### end Alembic commands ###
